ci: test
Signed-off-by: r3drun3 <simone.ragonesi@sighup.io>

diff --git a/.github/workflows/patch.yaml b/.github/workflows/patch.yaml
--- a/.github/workflows/patch.yaml
+++ b/.github/workflows/patch.yaml
@@ -94,11 +94,23 @@ jobs:
             COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
             COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
 
+        - name: Sign SBOM with Cosign
+          run: |
+            echo "${{ env.PATCHED_TAG_SBOM }}"
+            SBOM_FILE=$(find /tmp/sbom-action-* -name "*${{ env.PATCHED_TAG_SBOM }}*.spdx" -type f)
+            if [ -z "$SBOM_FILE" ]; then
+              echo "Error: .spdx file not found"
+              exit 1
+            fi
+            cosign sign --yes --key env://COSIGN_PRIVATE_KEY "${SBOM_FILE}"
+          env:
+            COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
+            COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
+
         - name: Attach SBOM to Image
           run: |
             echo "${{ env.PATCHED_TAG_SBOM }}"
             SBOM_FILE=$(find /tmp/sbom-action-* -name "*${{ env.PATCHED_TAG_SBOM }}*.spdx" -type f)
-
             if [ -z "$SBOM_FILE" ]; then
               echo "Error: .spdx file not found"
               exit 1
