ci: test
Signed-off-by: r3drun3 <simone.ragonesi@sighup.io>

diff --git a/.github/workflows/patch.yaml b/.github/workflows/patch.yaml
--- a/.github/workflows/patch.yaml
+++ b/.github/workflows/patch.yaml
@@ -93,10 +93,21 @@ jobs:
           env:
             COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
             COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
-        
+
         - name: Attach SBOM to Image
           run: |
-            cosign attach sbom --sbom "${{ env.PATCHED_TAG_SBOM }}.spdx" "ghcr.io/r3drun3/immunize/${{ steps.copa.outputs.patched-image }}"
+            SBOM_FILE=$(find /tmp -name "*${{ env.PATCHED_TAG_SBOM }}*.spdx" -type f)
+
+            if [ -z "$SBOM_FILE" ]; then
+              echo "Error: .spdx file not found"
+              exit 1
+            fi
+            cosign attach sbom --sbom "${SBOM_FILE}" "ghcr.io/r3drun3/immunize/${{ steps.copa.outputs.patched-image }}"
+    
+        
+        # - name: Attach SBOM to Image
+        #   run: |
+          # cosign attach sbom --sbom "${{ env.PATCHED_TAG_SBOM }}.spdx" "ghcr.io/r3drun3/immunize/${{ steps.copa.outputs.patched-image }}"
           # env:
           #   PATCHED_TAG_SBOM: ${{ env.PATCHED_TAG_SBOM }}.spdx
 
